name: CI - Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Install NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Show ls
        run: ls -la

      - name: Install NPM dependecies
        run: yarn install

      - name: Run tests
        run: yarn test:unit
